config/routes.rb
Rails.application.routes.draw do

  root 'homepages#index'

  devise_for :users, :controllers => { registrations: 'registrations' }

  post '/equipments' => 'equipments#create', as: :equipment_index # POURQUOI ????
  post '/homepages/addBasket/:id' => 'homepages#addBasket', as: :addBasket
  resources :users, :classes, :equipments, :baskets  

  get '/search' => 'homepages#search'
  

end

app/models/basket.rb
class Basket < ActiveRecord::Base
	has_many :orders
	belongs_to :user
end

app/models/classe.rb
class Classe < ActiveRecord::Base
	has_many :users
	has_many :equip_classes
	validates_presence_of :name, message: "Le nom de la classe ne doit pas être vide"
	validates_uniqueness_of :name, scope: :name, message: "Nom de classe déjà utilisé"
end

app/models/equip_class.rb
class EquipClass < ActiveRecord::Base
	belongs_to :classe
	belongs_to :equipment
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	has_many :classes
	has_and_belongs_to_many :orders
	has_one :material

	validates_presence_of :name, message: "Le nom ne doit pas être vide"
	validates_presence_of :item, message: "L'item ne doit pas être vide"
	validates_presence_of :location, message: "L'emplacement ne doit pas être vide"
	validates_presence_of :level, message: "Le niveau ne doit pas être vide"
	validates_presence_of :price, message: "Le prix ne doit pas être vide"
	validates_uniqueness_of :name, scope: :name, message: "Cet élément est déjà utilisé"
end

app/models/material.rb
class Material < ActiveRecord::Base
	validates_presence_of :name, message: "Le nom ne doit pas être vide"
	belongs_to :equipment
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :basket
	belongs_to :equipment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :baskets
	belongs_to :classe

	validates_presence_of :nickname, message: "Le nom ne doit pas être vide"
	# validates_presence_of :level, message: "Le niveau ne doit pas être vide"
	# validates_presence_of :loot, message: "Le butin ne doit pas être vide"
	validates_uniqueness_of :nickname, scope: :nickname, message: "est déjà pris par un autre aventurier"	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
	def index
	end
end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController

	def index
		@classes = Classe.all
	end

	def show
		@classe = Classe.find(params[:id])
	end

	def new
		@classe = Classe.new
	end

	def create
		@classe = Classe.new(classe_param)
		if @classe.save
			redirect_to classes_path, notice: "La classe \"#{@classe.name}\" a été ajoutée avec succés"
		else
			render 'new'
		end
	end

	def edit
		@classe = Classe.find(params[:id])
	end

	def update
		@classe = Classe.find(params[:id])
		oldname = @classe.name
		if @classe.update(classe_param)
			if @classe.name == oldname
				redirect_to classes_path, notice: "#{@classe.name} a été modifié avec succés"
			else
				redirect_to classes_path, notice: "#{oldname} a été modifié en #{@classe.name} avec succés"
			end
		else
			render 'edit'
		end
	end

	def destroy
		@classe = Classe.find(params[:id])
		@classe.destroy

		redirect_to classes_path, notice: "La classe \"#{@classe.name}\" a été supprimée avec succés"
	end
	

	private

	def classe_param
		params.require(:classe).permit(:name)
	end


end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController

	def index
		@equipments = Equipment.all
	end

	def show
		@equipment = Equipment.find(params[:id])
	end

	def new
		@equipment = Equipment.new
		@materials = Material.all
	end

	def create
		@equipment = Equipment.new(equipment_param)
		if @equipment.save
			redirect_to equipments_path, notice: "\"#{@equipment.name}\" a été ajouté(e) avec succés"
		else
			render 'new'
		end
	end


	def edit
		@equipment = Equipment.find(params[:id])
	end

	def update
		@equipment = Equipment.find(params[:id])
		oldname = @equipment.name
		if @equipment.update(equipment_param)
			if @equipment.name == oldname
				redirect_to equipments_path, notice: "#{@equipment.name} a été modifié avec succés"
			else
				redirect_to equipments_path, notice: "#{oldname} a été modifié en #{@equipment.name} avec succés"
			end
		else
			render 'edit'
		end
	end

	def destroy
		@equipment = Equipment.find(params[:id])
		@equipment.destroy

		redirect_to equipments_path, notice: "\"#{@equipment.name}\" a été supprimé(e) avec succés"
	end


	private

	def equipment_param
		params.require(:equipment).permit(:name, :item, :location, :price, :level, :bonus, :material)
	end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController

	def index
		@equipments = Equipment.all
	end

	def search
		sql = "SELECT * FROM equipment WHERE "
		where = ""

		if params[:name] != ""
			where += "name LIKE '%" + params[:name] + "%' AND "
		end
		if params[:item] != ""
			where += "item LIKE '%" + params[:item] + "%' AND "
		end

		if where != ""
			where = where.first(where.length - 5)
			sql += where
		else
			sql = sql.first(sql.length - 7)
		end
		
		@equipments = Equipment.find_by_sql(sql)

		render 'index'
	end

	# Action click on the button "buy"
	def addBasket
		# si pas de panier -> création d'un panier
		basket = Basket.new(user_id: current_user.id)
		# binding.pry
		if basket.save
			# ajout de l'article au panier
			# binding.pry
			order = Order.new(basket_id: basket.id, equipment_id: params[:id])
			if order.save
				redirect_to baskets_path, :method => :get
			else
				render 'homepages#index'
			end
		else
			# binding.pry
			render 'homepages#index'
		end
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_param)
		@user.nickname = @user.nickname.capitalize
		if @user.save
			redirect_to users_path, notice: "\"#{@user.nickname}\" a été ajouté(e) avec succés"
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		oldname = @user.nickname
		if @user.update(user_param)
			if @user.nickname == oldname
				redirect_to users_path, notice: "#{@user.nickname} a été modifié avec succés"
			else
				redirect_to users_path, notice: "#{oldname} a été modifié en #{@user.nickname} avec succés"
			end
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		
		redirect_to users_path, notice: " \"#{@user.nickname}\" a été supprimé(e) avec succés"
	end

	private

	def user_param
		params.require(:user).permit(:nickname, :level, :loot, :classe_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/baskets/index.haml
%h1 Mon panier

app/views/classes/edit.haml
%h1 Modification de la classe #{@classe.name} :

= form_for(@classe) do |f|
	- if @classe.errors.any?
		%ul
		- @classe.errors.each do |a, message|
			%li.warning= message
	
	= f.label 'Classe :'
	= f.text_field :name
	= f.submit 'Modifier', :class => 'btn'

= button_to "Retour", classes_path, :method => :get, :class => 'btn'

app/views/classes/index.haml
%h1 Liste des classes

%p#notice= notice

%ul.list-group#tableau
	- @classes.each do |c|
		%li.list-group-item
			=link_to 'suppr', class_path(c), :method => :delete, data: { confirm: 'Voulez-vous vraiment supprimer l\'aventurier ?' }, :class => 'badge'
			=link_to 'modif', edit_class_path(c), :method => :get, :class => 'badge'
			=link_to 'voir', class_path(c), :method => :get, :class => 'badge'
			= c.name

= button_to "Créer une nouvelle classe", new_class_path, :method => :get, :class => 'btn'

app/views/classes/new.haml
%h1 Ajout d'une classe
= form_for(@classe) do |f|
	- if @classe.errors.any?
		%ul
		- @classe.errors.each do |a, message|
			%li.warning= message
	
	= f.label 'Nom de classe :'
	= f.text_field :name
	= f.submit 'Ajouter', :class => 'btn'


= button_to "Retour", classes_path, :method => :get, :class => 'btn'

app/views/classes/show.haml
%h1= @classe.name

= button_to "Retour", classes_path, :method => :get, :class => 'btn'

app/views/equipments/edit.haml
%h1 Modification de l'élément #{@equipment.name} :

= form_for(@equipment) do |f|
	- if @equipment.errors.any?
		%ul
		- @equipment.errors.each do |message|
			%li.warning= message
	
	= f.label 'Nom :'
	= f.text_field :name
	= f.label 'Item :'
	= f.text_field :item
	= f.label 'Emplacement :'
	= f.text_field :location
	= f.label 'Matière :'
	= f.text_field :material
	= f.label 'Prix :'
	= f.text_field :price
	= f.label 'Niveau :'
	= f.text_field :level
	= f.label 'Bonus :'
	= f.text_field :bonus
	= f.submit 'Modifier', :class => 'btn'

= button_to "Retour", equipments_path, :method => :get, :class => 'btn'
	

app/views/equipments/index.haml
%h1 Liste des équipements

%p#notice= notice

%ul.list-group#tableau
	- @equipments.each do |e|
		%li.list-group-item
			=link_to 'suppr', equipment_path(e), :method => :delete, data: { confirm: 'Voulez-vous vraiment supprimer l\'aventurier ?' }, :class => 'badge'
			=link_to 'modif', edit_equipment_path(e), :method => :get, :class => 'badge'
			=link_to 'voir', equipment_path(e), :method => :get, :class => 'badge'
			= e.name

= button_to "Ajouter un élément", new_equipment_path, :method => :get, :class => 'btn'

app/views/equipments/new.haml
%h1 Ajout d'élément

= form_for(@equipment) do |f|
	- if @equipment.errors.any?
		%ul
		- @equipment.errors.each do |a, message|
			%li.warning= message
	
	= f.label 'Nom :'
	= f.text_field :name 
	= f.label 'Item :'
	= f.text_field :item
	= f.label 'Emplacement :'
	= f.text_field :location
	= f.label 'Matière :'
	= f.text_field :material
	= f.label 'Prix :'
	= f.text_field :price
	= f.label 'Niveau :'
	= f.text_field :level
	= f.label 'Bonus :'
	= f.text_field :bonus
	= f.submit 'Ajouter', :class => 'btn'

= button_to "Retour", equipments_path, :method => :get, :class => 'btn'


-#= f.collection_select :provider_id, Provider.order(:name),:id,:name, include_blank: true

app/views/equipments/show.haml
%h1= @equipment.name

.panel.panel-primary
	.panel-heading Informations générales
	.panel-body
		%p= "Item: #{@equipment.item}"
		%p= "Emplacement: #{@equipment.location}"
		%p= "Matiére: #{@equipment.material}"
		%p= "Niveau: #{@equipment.level}"
		%p= "Bonus: #{@equipment.bonus}"
		%p= "Prix: #{@equipment.price}"
		%p= @classes

= button_to "Retour", equipments_path, :method => :get, :class => 'btn'

app/views/homepages/index.haml
%h1 Bonjour Aventurier ! Que recherchez-vous?

%br

/ = form_tag("/search", method: "get") do
/ 	.input-group
/ 		%span#basic-addon1.input-group-addon Nom
/ 		%input.form-control{"aria-describedby" => "basic-addon1", :type => "text"}
/ 		%span#basic-addon1.input-group-addon Item
/ 		%input.form-control{"aria-describedby" => "basic-addon1", :type => "text"}
/ 		%button.btn.btn-default{:type => "button"} Rechercher

= form_tag("/search", method: "get") do
	= label_tag(:name, "Nom:")
	= text_field_tag(:name)
	= label_tag(:item, "Item:")
	= text_field_tag(:item)
	= submit_tag "Rechercher", :class => 'btn'

%br

%table
	%thead
		%tr
			%th
				Nom
			%th
				Item
			%th
				Matiere	
			%th
				Emplacement
			%th
				Prix
			%th
				Niveau
			%th
				Bonus	
	%tbody
		- @equipments.each do |e|
			%tr
				%td
					= e.name
				%td
					= e.item
				%td
					= e.material
				%td
					= e.location
				%td
					= e.price
				%td
					= e.level
				%td
					= e.bonus
				%td
					=link_to 'Acheter', addBasket_path(e), :method => :post, :class => 'badge'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Armurerie</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<header class="navbar navbar-default">
			<div class="collapse navbar-collapse">
		    <div class="container">
		      <nav>
		        <ul class="nav navbar-nav">
		          <li><%= link_to "Home", root_path %></li>
		          <li><%= link_to "Aventuriers", users_path %></li>
		          <li><%= link_to "Classes", classes_path %></li>
		          <li><%= link_to "Equipements", equipments_path %></li>
		        </ul>
		        <ul class="nav navbar-nav navbar-right">
		        	<% if current_user %>
			        	<li class="dropdown">
				          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "#{current_user.nickname} " %><span class="caret"></span></a>
				          <ul class="dropdown-menu">
				            <li><%= link_to "Mon compte", user_path(current_user), method: :get %></li>
				            <!-- <li><a href="#">Panier</a></li>
				            <li><a href="#">Mes commandes</a></li> -->
				            <li role="separator" class="divider"></li>
				            <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></li>
				          </ul>
				        </li>
		        	<% end %>
		        </ul>
		      </nav>
		    </div>
			</div>
		</header>


	<%= yield %>

	</body>
</html>

app/views/users/edit.haml
%h1 Modification de l'aventurier #{@user.nickname} :

= form_for(@user) do |f|
	- if @user.errors.any?
		%ul
		- @user.errors.each do |a, message|
			%li.warning= message

	= f.label 'Aventurier :'
	= f.text_field :nickname
	= f.label 'Niveau :'
	= f.text_field :level
	= f.label 'Butin :'
	= f.text_field :loot
	= f.collection_select :classe_id, Classe.order(:name), :id, :name
	= f.submit 'Modifier', :class => 'btn'

= button_to "Retour", users_path, :method => :get, :class => 'btn'

app/views/users/index.haml
%h1 Liste des aventuriers

%p#notice= notice

%ul.list-group#tableau
	- @users.each do |u|
		%li.list-group-item
			=link_to 'suppr', user_path(u), :method => :delete, data: { confirm: 'Voulez-vous vraiment supprimer l\'aventurier ?' }, :class => 'badge'
			=link_to 'modif', edit_user_path(u), :method => :get, :class => 'badge'
			=link_to 'voir', user_path(u), :method => :get, :class => 'badge'
			= u.nickname

= button_to "Ajouter un aventurier", new_user_path, :method => :get, :class => 'btn'

app/views/users/new.haml
%h1 Ajout d'un aventurier

= form_for(@user) do |f|
	- if @user.errors.any?
		%ul
		- @user.errors.each do |a, message|
			%li.warning= message
			
	= f.label 'Aventurier :'
	= f.text_field :nickname
	= f.label 'Niveau :'
	= f.text_field :level
	= f.label 'Butin :'
	= f.text_field :loot
	= f.collection_select :classe_id, Classe.order(:name), :id, :name, include_blank: false
	= f.submit 'Ajouter', :class => 'btn'

= button_to "Retour", users_path, :method => :get, :class => 'btn'

app/views/users/show.haml
%h1= @user.nickname

.panel.panel-primary
	.panel-heading Informations générales
	.panel-body
		%p= "Niveau: #{@user.level}"
		%p= "Butin: #{@user.loot}"
		%p= "Classe: #{@user.classe.name}"

- if @user.baskets.any?
	.panel.panel-info
		.panel-heading Historique d'achats
		.panel-body
			- @user.baskets.each do |basket|
				%p
					= basket.updated_at.strftime("%d %b %Y")
					%ul
					- basket.orders.each do |order|
						%li.order
							= order.equipment.name
							= "(quantité: #{order.quantity})"

= button_to "Retour", users_path, :method => :get, :class => 'btn'